[package]
authors = ["Elliott Linder <elliott.darfink@gmail.com>"]
description = "A library for manipulating memory regions"
documentation = "https://docs.rs/region"
homepage = "https://github.com/darfink/region-rs"
keywords = ["region", "page", "lock", "protect", "maps"]
license = "MIT"
name = "region"
readme = "README.md"
repository = "https://github.com/darfink/region-rs"
version = "0.0.6"

[dependencies]
bitflags = "0.9.1"
errno = "0.2.3"
error-chain = "0.10.0"
lazy_static = "0.2.8"
libc = "0.2"

[dev-dependencies]
memmap = "0.5.2"

[target]

[target."cfg(target_os = \"linux\")".dependencies]
regex = "0.2.2"

[target."cfg(target_os = \"macos\")".dependencies]
mach = "0.1.0"

[target."cfg(windows)".dependencies]
kernel32-sys = "0.2.2"
winapi = "0.2"

[badges]
travis-ci = { repository = "darfink/region-rs", branch = "master" }
appveyor = { repository = "darfink/region-rs", branch = "master" }
