[package]
authors = ["Elliott Linder <elliott.darfink@gmail.com>"]
description = "A library for manipulating memory regions"
documentation = "https://docs.rs/region"
homepage = "https://github.com/darfink/region-rs"
keywords = ["region", "page", "lock", "protect", "maps"]
license = "MIT"
name = "region"
readme = "README.md"
repository = "https://github.com/darfink/region-rs"
version = "0.1.0"

[badges]

[badges.appveyor]
branch = "master"
repository = "darfink/region-rs"

[badges.travis-ci]
branch = "master"
repository = "darfink/region-rs"

[dependencies]
bitflags = "1.0"
errno = "0.2.3"
failure = "0.1.1"
libc = "0.2"

[dev-dependencies]
memmap = "0.5.2"

[target]

[target."cfg(target_os = \"macos\")"]

[target."cfg(target_os = \"macos\")".dependencies]
mach = "0.1.0"

[target."cfg(windows)"]

[target."cfg(windows)".dependencies]
kernel32-sys = "0.2.2"
winapi = "0.2"
