[package]
authors = ["Elliott Linder <elliott.darfink@gmail.com>"]
description = "A library for dealing with memory regions"
homepage = "https://github.com/darfink/region-rs"
license = "MIT"
name = "region"
readme = "README.md"
repository = "https://github.com/darfink/region-rs"
version = "0.1.0"

[dependencies]
errno = "0.1.8"
lazy_static = "0.2.1"
libc = "0.2"
bitflags = "0.7"

[target."cfg(target_os = \"macos\")".dependencies]
mach = "0.0.6"

[target."cfg(target_os = \"linux\")".dependencies]
regex = "0.1.80"

[target."cfg(windows)".dependencies]
winapi = "0.2"

[dev-dependencies]
memmap = "0.5.0"
