parameters:
  # The rust channels to use ('stable', 'beta' and 'nightly')
  channels: [stable]
  # The target triples to use (e.g 'i686-apple-darwin')
  targets: []

jobs:
- ${{ each target in parameters.targets }}:
  - ${{ if target.channels }}:
    - ${{ each channel in target.channels }}:
      - template: jobs-single-rust.yml
        parameters:
          identifier: ${{ format('rust_{0}_{1}', channel, join('_', target.target)) }}
          channel: ${{ channel }}
          ${{ insert }}: ${{ target }}

  - ${{ if not(target.channels) }}:
    - ${{ each channel in parameters.channels }}:
      - template: jobs-single-rust.yml
        parameters:
          identifier: ${{ format('rust_{0}_{1}', channel, join('_', target.target)) }}
          channel: ${{ channel }}
          ${{ insert }}: ${{ target }}